// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vrasrgzjxqrvkvgwsbac.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZyYXNyZ3pqeHFydmt2Z3dzYmFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1OTAyMTAsImV4cCI6MjA1OTE2NjIxMH0.fEFXId65qqDwqnO-so1sNb7MS8n7I0K2r0S2D13SKfo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);